const majorsList = [
  "Accounting",
  "Actuarial Science",
  "Advertising",
  "Agricultural Economics",
  "Agronomy",
  "Anthropology",
  "Archaeology",
  "Architecture",
  "Art History",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classics",
  "Communications",
  "Computer Science",
  "Criminal Justice",
  "Cultural Studies",
  "Dance",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Finance",
  "French",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Industrial Engineering",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Liberal Arts",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Religious Studies",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish",
  "Sports Management",
  "Theater",
  "Veterinary Science",
  "Women's Studies",
  "Zoology",
  "Other"
];

export default majorsList;