const universitiesList = [
  "Florida A&M University",
  "Florida Atlantic University",
  "Florida Gulf Coast University",
  "Florida International University",
  "Florida Polytechnic University",
  "Florida State University",
  "New College of Florida",
  "University of Central Florida",
  "University of Florida",
  "University of North Florida",
  "University of South Florida",
  "University of West Florida",
  "Broward College",
  "Chipola College",
  "College of Central Florida",
  "Daytona State College",
  "Eastern Florida State College",
  "Florida Gateway College",
  "College of the Florida Keys",
  "Florida SouthWestern State College",
  "Florida State College at Jacksonville",
  "Gulf Coast State College",
  "Hillsborough Community College",
  "Indian River State College",
  "Lake-Sumter State College",
  "Miami Dade College",
  "North Florida College",
  "Northwest Florida State College",
  "Palm Beach State College",
  "Pasco-Hernando State College",
  "Pensacola State College",
  "Polk State College",
  "Santa Fe College",
  "Seminole State College of Florida",
  "South Florida State College",
  "St. Johns River State College",
  "St. Petersburg College",
  "State College of Florida, Manatee-Sarasota",
  "Tallahassee State College",
  "Valencia College",
  "Other"
];

export default universitiesList;